# Generated by Django 4.2.4 on 2023-08-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Decription', models.CharField(max_length=500)),
                ('Food_type', models.CharField(choices=[('veg', 'VEG'), ('nonveg', 'NONVEG')], default='veg', max_length=6)),
                ('Recipe_Created', models.DateField()),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
