# Generated by Django 4.2.4 on 2023-08-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Image',
            field=models.CharField(max_length=100),
        ),
    ]
