# Generated by Django 4.2.4 on 2023-08-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Food_type',
            field=models.CharField(max_length=6),
        ),
    ]
