# Generated by Django 4.2.4 on 2023-08-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_food_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Image',
            field=models.CharField(max_length=2000),
        ),
    ]
