# Generated by Django 4.2.4 on 2023-08-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Decription',
            field=models.TextField(max_length=1000),
        ),
    ]
