# Generated by Django 4.2.4 on 2023-08-16 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_delete_productslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='date_and_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 16, 10, 3, 51, 776986)),
        ),
        migrations.AddField(
            model_name='product',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
