# Generated by Django 4.2.4 on 2023-08-16 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_archived_product_date_and_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_and_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 16, 10, 7, 41, 942465)),
        ),
    ]
