# Generated by Django 4.2.4 on 2023-08-16 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_and_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 16, 10, 30, 50, 995094)),
        ),
    ]
