# Generated by Django 4.2.4 on 2023-08-17 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=100)),
                ('Exam_Date', models.DateField()),
                ('Max_Score', models.PositiveIntegerField(default=93)),
                ('Actual_Score', models.PositiveIntegerField()),
                ('student_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
            options={
                'verbose_name_plural': 'Exam Details',
            },
        ),
    ]
