# Generated by Django 4.2.4 on 2023-08-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='Total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
